# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20160601_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
