# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_course_is_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('sifra', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
