# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_finishededucation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='finishededucation',
            options={'ordering': ('description',)},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ('description',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
    ]
