# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20160604_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultscourse',
            old_name='success_course_3_4',
            new_name='success_course_4',
        ),
        migrations.AddField(
            model_name='resultscourse',
            name='success_course_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsmatura',
            name='general_success_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsmatura',
            name='general_success_4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
