# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20160609_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultscourse',
            name='success_course_3_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultscourse',
            name='success_course_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultscourse',
            name='success_course_4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
