# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20160612_1726'),
        ('applications', '0006_auto_20160612_1831'),
    ]

    operations = [
    ]
