# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_programs', '0001_initial'),
        ('information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=45)),
                ('house_number', models.IntegerField()),
                ('additive', models.CharField(blank=True, max_length=1, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='information.Country')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='information.Post')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='information.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('irregular', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emso', models.CharField(max_length=45)),
                ('second_last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('male', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField()),
                ('city_of_birth', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('application_code', models.CharField(max_length=45)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Address')),
                ('address_for_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_for_notice', to='students.Address')),
                ('application', models.ManyToManyField(through='students.Applications', to='study_programs.StudyProgram')),
                ('country_of_birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_of_birth', to='information.Country')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Nationality')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='applications',
            name='study_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_programs.StudyProgram'),
        ),
    ]
