# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20160602_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='additive',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Hišni dodatek'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='information.Country', verbose_name='Država'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.IntegerField(verbose_name='Hišna številka'),
        ),
        migrations.AlterField(
            model_name='address',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='information.Post', verbose_name='Pošta'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='information.Region', verbose_name='Občina'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=45, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='irregular',
            field=models.BooleanField(default=False, verbose_name='Način študija'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='study_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_programs.StudyProgram', verbose_name='Študijski program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Address', verbose_name='Stalno prebivališče'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_for_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_for_notice', to='students.Address', verbose_name='Naslov za obveščanje'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city_of_birth',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Mesto rojstva'),
        ),
        migrations.AlterField(
            model_name='student',
            name='country_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_of_birth', to='information.Country', verbose_name='Država rojstva'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Datum rojstva'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emso',
            field=models.CharField(blank=True, max_length=45, verbose_name='EMŠO'),
        ),
        migrations.AlterField(
            model_name='student',
            name='finished_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.FinishedEducation', verbose_name='Končana izobrazba'),
        ),
        migrations.AlterField(
            model_name='student',
            name='male',
            field=models.BooleanField(default=True, verbose_name='Spol'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Nationality', verbose_name='Državljanstvo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Telefonska številka'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Dekliški priimek'),
        ),
    ]
