# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20160603_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
