# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20160608_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
