# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20160609_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='points_general_success',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='points_matura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='points_priority_course',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
