# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '__first__'),
        ('information', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_matura', models.FloatField()),
                ('w_general_success', models.FloatField()),
                ('w_priority_course_3_4', models.FloatField(blank=True, null=True)),
                ('w_priority_course_matura', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionMatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_matura', models.FloatField()),
                ('w_general_success', models.FloatField()),
                ('w_matura_course', models.FloatField(blank=True, null=True)),
                ('w_priority_course_3_4', models.FloatField(blank=True, null=True)),
                ('w_priority_course_matura', models.FloatField(blank=True, null=True)),
                ('matura_courses', models.ManyToManyField(to='information.Course')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Profession')),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_slots_EU', models.IntegerField(default=0)),
                ('enrolment_slots_other', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=45, verbose_name='Šifra')),
                ('name', models.CharField(max_length=100, verbose_name='Ime')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.Faculty')),
                ('general_matura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_programs.GeneralMatura')),
                ('irregular_slots', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irregular_slots', to='study_programs.Slots')),
                ('priority_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Course')),
                ('profession_matura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_programs.ProfessionMatura')),
                ('regular_slots', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_programs.Slots')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=45)),
                ('profession', models.BooleanField(default=False)),
                ('course', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='type_requirements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_programs.TypeRequirements'),
        ),
    ]
