# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='enrolment_slots_EU',
            field=models.IntegerField(default=0, verbose_name='Vpisna mesta za državljane EU'),
        ),
        migrations.AlterField(
            model_name='slots',
            name='enrolment_slots_other',
            field=models.IntegerField(default=0, verbose_name='Vpisna mesta za ostale'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.Faculty', verbose_name='Fakulteta'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='general_matura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_programs.GeneralMatura', verbose_name='Splošna matura'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='irregular_slots',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irregular_slots', to='study_programs.Slots', verbose_name='Izredni'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='priority_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Course', verbose_name='Prioritetni predmet'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='profession_matura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_programs.ProfessionMatura', verbose_name='Poklicna matura'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='regular_slots',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_programs.Slots', verbose_name='Redni'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='type_requirements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_programs.TypeRequirements', verbose_name='Vpisni pogoj'),
        ),
    ]
